### ISSUE TITLE
W3C TPAC 2015 - Post-meeting TODO list

### ISSUE THREAD

**Issue by msporny** [opencreds/website#14]
# Documentation
- [x] Create proposal for Credentials Task Force in Web Payments IG (@msporny)
- [ ] Refine proposal for Credentials Task Force in Web Payments IG
- [ ] Create proposal for Fast Track Linked Data Platform WG (LD-Patch and RDF Dataset Normalization)
- [ ] Create comparison between Identity Credentials and OpenID Connect
- [ ] Create comparison between Identity Credentials and SAML
- [ ] Create comparison between Linked Data Signatures and JOSE
- [ ] Create Linked Data Key Management specification
- [ ] Create comparison between cant.py and Aidan Hogan's algorithms
# Standards Implementation Foundation
- [x] Board of Directors for Standards Implementation Foundation (@erickorb)
- [x] Advisory Committee for Standards Implementation Foundation (@erickorb)
# Outreach
- [x] Demo Identity Credentials to MIT CSAIL research group (@msporny)
- [ ] Ask Wendy Seltzer who needs to be consulted about the groups plans
- [ ] Ask Brad Hill how he'd solve the problem
- [ ] Ask Jeff Hodges how he'd solve the problem
- [ ] Ask Harry Halpin how he'd solve the problem
- [ ] Ask Dick Hardt how he'd solve the problem

**Comment by msporny** [comment]
Create proposal for Credentials Task Force in Web Payments IG is done:

https://www.w3.org/Payments/IG/wiki/Main_Page/ProposalsQ42015/Credentials
